# Navigation Links
#   To link a homepage section, use a hash `#` followed by the section ID.
#   The weight parameter defines the order that the links appear.

main:
  - name: 소개 자료
    url: /#skills
    weight: 10
  - name: 대표 도서
    url: /#projects
    weight: 20
  - name: 주요 경력
    url: /#experience
    weight: 30
  # - name: Blog
    # url: /#blog
    # weight: 40
  - name: 강의·연수·컨설팅 문의
    url: /#contact-wrapper
    weight: 50
